typeset -U path manpath

path=(
    ~/.local/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    $path
)

manpath=(
    /usr/local/share/man
    /usr/share/man
    $manpath
)

export EDITOR="emacs -nw"
export LANG=en_US.UTF-8
export TERM=xterm-256color
export VISUAL=emacs
